/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TreinarLangNivelRouteImport } from './routes/treinar.$lang.$nivel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinarLangNivelRoute = TreinarLangNivelRouteImport.update({
  id: '/treinar/$lang/$nivel',
  path: '/treinar/$lang/$nivel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
  '/terminal': typeof TerminalRoute
  '/treinar/$lang/$nivel': typeof TreinarLangNivelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
  '/terminal': typeof TerminalRoute
  '/treinar/$lang/$nivel': typeof TreinarLangNivelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
  '/terminal': typeof TerminalRoute
  '/treinar/$lang/$nivel': typeof TreinarLangNivelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/professor'
    | '/progresso'
    | '/terminal'
    | '/treinar/$lang/$nivel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/painel'
    | '/professor'
    | '/progresso'
    | '/terminal'
    | '/treinar/$lang/$nivel'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/professor'
    | '/progresso'
    | '/terminal'
    | '/treinar/$lang/$nivel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRoute
  ProfessorRoute: typeof ProfessorRoute
  ProgressoRoute: typeof ProgressoRoute
  TerminalRoute: typeof TerminalRoute
  TreinarLangNivelRoute: typeof TreinarLangNivelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinar/$lang/$nivel': {
      id: '/treinar/$lang/$nivel'
      path: '/treinar/$lang/$nivel'
      fullPath: '/treinar/$lang/$nivel'
      preLoaderRoute: typeof TreinarLangNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRoute,
  ProfessorRoute: ProfessorRoute,
  ProgressoRoute: ProgressoRoute,
  TerminalRoute: TerminalRoute,
  TreinarLangNivelRoute: TreinarLangNivelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
